services:
  postgresql:
    image: docker.io/postgres:14.7-alpine
    restart: always
    command: -c 'max_connections=200'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data

  cube_api:
    restart: always
    image: borodark/cube:dev #docker.io/cubejs/cube:latest
    ports:
      - 4008:4000
    environment:
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_NAME: power_of_3_repo
      CUBEJS_DB_HOST: postgresql
      CUBEJS_DB_USER: postgres
      CUBEJS_DB_PASS: postgres
      CUBEJS_CUBESTORE_HOST: cubestore_router
      CUBEJS_API_SECRET: secret
      CUBEJS_DEV_MODE: "TRUE"
      CUBEJS_ADBC_PORT: 8120
      CUBESQL_LOG_LEVEL: trace
      CUBESQL_ARROW_RESULTS_CACHE_ENABLED: false

    volumes:
      - ./:/cube/conf
    depends_on:
      - cube_refresh_worker
      - cubestore_router
      - cubestore_worker_1
      - cubestore_worker_2

  cube_refresh_worker:
    restart: always
    image: borodark/cube:dev #docker.io/cubejs/cube:latest
    environment:
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_NAME: power_of_3_repo
      CUBEJS_DB_HOST: postgresql
      CUBEJS_DB_USER: postgres
      CUBEJS_DB_PASS: postgres
      ######
      #CUBEJS_DB_HOST: cockroach
      #CUBEJS_DB_USER: admin
      #CUBEJS_DB_PASS: admin
      #CUBEJS_DB_PORT: 26257
      CUBEJS_CUBESTORE_HOST: cubestore_router
      CUBEJS_API_SECRET: secret
      CUBEJS_REFRESH_WORKER: "TRUE"
    volumes:
      - ./:/cube/conf

  cubestore_router:
    restart: always
    image: borodark/cubestore:dev #docker.io/cubejs/cubestore:latest
    environment:
      CUBESTORE_WORKERS: cubestore_worker_1:10001,cubestore_worker_2:10002
      CUBESTORE_REMOTE_DIR: /cube/data
      CUBESTORE_META_PORT: 9999
      CUBESTORE_SERVER_NAME: cubestore_router:9999
    volumes:
      - .cubestore:/cube/data

  cubestore_worker_1:
    restart: always
    image: borodark/cubestore:dev # docker.io/cubejs/cubestore:latest
    environment:
      CUBESTORE_WORKERS: cubestore_worker_1:10001,cubestore_worker_2:10002
      CUBESTORE_SERVER_NAME: cubestore_worker_1:10001
      CUBESTORE_WORKER_PORT: 10001
      CUBESTORE_REMOTE_DIR: /cube/data
      CUBESTORE_META_ADDR: cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router

  cubestore_worker_2:
    restart: always
    image: borodark/cubestore:dev # docker.io/cubejs/cubestore:latest
    environment:
      CUBESTORE_WORKERS: cubestore_worker_1:10001,cubestore_worker_2:10002
      CUBESTORE_SERVER_NAME: cubestore_worker_2:10002
      CUBESTORE_WORKER_PORT: 10002
      CUBESTORE_REMOTE_DIR: /cube/data
      CUBESTORE_META_ADDR: cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router

volumes:
  postgresql:
